Fix/did peer generation
ADORSYS-GIS/wallet-vc-libs pull request #59
Opened 2024-12-11 10:54 UTC by forkimenjeckayang

This PR adjusts the required chnages to have the did:peer:generator work for our use case, it intoduces
- New algorithm for key genration (X25519) keys
- Tests refinement

2024-12-13 10:43 UTC, Ogenbertrand requested changes

2024-12-13 10:43 UTC, Ogenbertrand commented on packages/multiple-did-identities/src/__tests__/generate-key-pair.spec.ts
> +});
The assertions for public/private keys and JWKs are repetitive across the tests. You could use a helper function to validate the structure of a key pair to improve readability, WDYT @forkimenjeckayang. ?

2024-12-13 10:56 UTC, Ogenbertrand commented
Add tests for scenarios where invalid input is passed to generateKeyPairs, such as negative numbers or zero.

2024-12-13 11:04 UTC, Ogenbertrand requested changes

2024-12-13 11:04 UTC, Ogenbertrand commented on packages/multiple-did-identities/src/utils/generateKeyPairs.ts
> +    const publicKeyJwk: JWKKeys = {
Instead of hardcoding the structure of publicKeyJwk and privateKeyJwk, you could dynamically validate them against a schema right ?.

2024-12-13 11:04 UTC, Ogenbertrand commented on packages/multiple-did-identities/src/utils/generateKeyPairs.ts
> +    const publicKeyJwk: JWKKeys = {
same thing here too.

2024-12-13 11:15 UTC, Ogenbertrand commented on packages/multiple-did-identities/src/__tests__/did-peer-2-service.spec.ts
Isn't it alright to create test fixtures, to reduce reusability among the code base?

2024-12-13 11:15 UTC, Ogenbertrand commented on packages/multiple-did-identities/src/__tests__/did-peer-3-service.spec.ts
I think implementing test fixtures in the test base will help reduce usability. WDYT its up to you to do this when you find time right!.

2024-12-14 11:39 UTC, hugoib commented
It looks good! I added a comment that will be necessary to address so the did peers will be able to be used in further steps. (For packing the message, the id of the private key should have the previously shown format). Thank you!

2024-12-16 07:52 UTC, Ogenbertrand commented
LGTM.

2024-12-16 07:53 UTC, Ogenbertrand commented
It can be close after the response from @hugoib.

2024-12-17 13:55 UTC, IngridPuppet commented on packages/multiple-did-identities/src/tests/testFixtures.ts
> +    type: 'JsonWebKey2020',
Looks like there are no tests for the structure of the id.

2024-12-18 11:38 UTC, IngridPuppet approved these changes

2024-12-18 11:46 UTC, merged